name: aeyrium_sensor
description: A Flutter sensor plugin which provide easy access to the Pitch and Roll on Android and iOS devices.
version: 1.1.0
authors:
  - Aeyrium Inc. <diego@aeyrium.com>
  - Diego Velásquez <diego.velasquez.lopez@gmail.com>
homepage: https://aeyrium.com/
repository: https://github.com/aeyrium/aeyrium-sensor

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.aeyrium.sensor
    pluginClass: AeyriumSensorPlugin
